kind: pipeline
type: ssh
name: 部署321CQU微信相关模块

server:
  host:
    from_secret: ssh_host
  user: root
  ssh_key:
    from_secret: ssh_key

platform:
  os: linux
  arсh: amd64

clone:
  disable: true

steps:
- name: clone
  commands:
    - git config --global http.proxy http://127.0.0.1:7890
    - git config --global https.proxy http://127.0.0.1:7890
    - git clone https://github.com/ZhuLegend/321CQU_Wechat_Manager.git
    - cd ./321CQU_Wechat_Manager/
    - git checkout main

- name: 新建镜像
  commands:
    - cd ./321CQU_Wechat_Manager/
    - docker-compose build
    - docker-compose up -d
    - docker image prune -f
  depends_on:
    - clone

trigger:
  branch:
  - main
  event:
  - push
  - merge

---
kind: pipeline
type: docker
name: 通知

clone:
  disable: true

steps:
  - name: 钉钉通知
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      secret:
        from_secret: dingtalk_sign
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true

depends_on:
  - 部署321CQU微信相关模块
