version: '3'
services:

  api-gateway:
    container_name: 321cqu-wechat
    build: .
    ports:
     - "8321:8321"
    restart: always
    volumes:
      - /www/services/wechat_manager/logs:/src/logs
      - /www/services/wechat_manager/config.cfg:/src/utils/config.cfg
      - /www/services/_321CQU_package/python_package:/_321CQU_package
    environment:
      PYTHONPATH: /_321CQU_package
    networks:
      - persist

networks:
  persist:
    external:
      name: 321cqu